# Generated by Django 6.0.4 on 2026-04-13 07:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon_name', models.CharField(help_text='圖示名稱或識別字串（供前端顯示）', max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '產業領域',
                'verbose_name_plural': '產業領域',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField(verbose_name='場景描述')),
                ('current_solution', models.TextField(verbose_name='現狀')),
                ('pain_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('potential_value', models.TextField(verbose_name='潛在價值')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_points', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pain_points', to='collaboration.category')),
            ],
            options={
                'verbose_name': '痛點',
                'verbose_name_plural': '痛點',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('expert', 'Expert'), ('engineer', 'Engineer')], default='engineer', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者檔案',
                'verbose_name_plural': '使用者檔案',
            },
        ),
    ]
